export const data = {
    week: {
        limit: "5",
        data: [
            { label: "Пн", numberOfPatients: "3", },
            { label: "Вт", numberOfPatients: "2", },
            { label: "Ср", numberOfPatients: "1", },
            { label: "Чт", numberOfPatients: "0", },
            { label: "Пт", numberOfPatients: "2", },
            { label: "Сб", numberOfPatients: "5", },
            { label: "Вс", numberOfPatients: "1", },
        ],
    },
    month: {
        limit: "6",
        data: [
            { label: "1", numberOfPatients: "3", },
            { label: "2", numberOfPatients: "2", },
            { label: "3", numberOfPatients: "1", },
            { label: "4", numberOfPatients: "3", },
            { label: "5", numberOfPatients: "2", },
            { label: "6", numberOfPatients: "5", },
            { label: "7", numberOfPatients: "10", },
            { label: "8", numberOfPatients: "3", },
            { label: "9", numberOfPatients: "6", },
            { label: "10", numberOfPatients: "3", },
            { label: "11", numberOfPatients: "2", },
            { label: "12", numberOfPatients: "0", },
            { label: "13", numberOfPatients: "3", },
            { label: "14", numberOfPatients: "2", },
            { label: "15", numberOfPatients: "5", },
            { label: "16", numberOfPatients: "1", },
            { label: "17", numberOfPatients: "3", },
            { label: "18", numberOfPatients: "6", },
            { label: "19", numberOfPatients: "3", },
            { label: "20", numberOfPatients: "2", },
            { label: "21", numberOfPatients: "1", },
            { label: "22", numberOfPatients: "3", },
            { label: "23", numberOfPatients: "2", },
            { label: "24", numberOfPatients: "5", },
            { label: "25", numberOfPatients: "1", },
            { label: "26", numberOfPatients: "3", },
            { label: "27", numberOfPatients: "6", },
            { label: "28", numberOfPatients: "2", },
            { label: "29", numberOfPatients: "3", },
            { label: "30", numberOfPatients: "4", },
            { label: "31", numberOfPatients: "5", },
        ],
    },
    year: {
        limit: "11",
        data: [
            { label: "Январь", numberOfPatients: "1", },
            { label: "Февраль", numberOfPatients: "3", },
            { label: "Март", numberOfPatients: "6", },
            { label: "Апрель", numberOfPatients: "1", },
            { label: "Май", numberOfPatients: "10", },
            { label: "Июнь", numberOfPatients: "3", },
            { label: "Июль", numberOfPatients: "11", },
            { label: "Август", numberOfPatients: "4", },
            { label: "Сентябрь", numberOfPatients: "4", },
            { label: "Октябрь", numberOfPatients: "2", },
            { label: "Ноябрь", numberOfPatients: "5", },
            { label: "Декабрь", numberOfPatients: "0", },
        ],
    },
}